import { Meta } from "#src/services/StockServices.types.ts";

export const mockStocks: Meta[] = [
  {
    symbol: "AAPL",
    shortName: "Apple Inc.",
    regularMarketPrice: 175.68,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: 2.85,
    regularMarketChangePercent: 1.64,
    regularMarketPreviousClose: 172.83,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "GOOGL",
    shortName: "Alphabet Inc. (Class A)",
    regularMarketPrice: 2845.22,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: -14.56,
    regularMarketChangePercent: -0.51,
    regularMarketPreviousClose: 2859.78,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "MSFT",
    shortName: "Microsoft Corporation",
    regularMarketPrice: 299.81,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: 4.31,
    regularMarketChangePercent: 1.46,
    regularMarketPreviousClose: 295.5,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "AMZN",
    shortName: "Amazon.com, Inc.",
    regularMarketPrice: 3442.44,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: 1.19,
    regularMarketChangePercent: 0.03,
    regularMarketPreviousClose: 3441.25,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "TSLA",
    shortName: "Tesla, Inc.",
    regularMarketPrice: 722.52,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: -15.92,
    regularMarketChangePercent: -2.15,
    regularMarketPreviousClose: 738.44,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "NFLX",
    shortName: "Netflix, Inc.",
    regularMarketPrice: 670.25,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: 12.88,
    regularMarketChangePercent: 1.96,
    regularMarketPreviousClose: 657.37,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "NVDA",
    shortName: "NVIDIA Corporation",
    regularMarketPrice: 313.58,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: -7.68,
    regularMarketChangePercent: -2.39,
    regularMarketPreviousClose: 321.26,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "INTC",
    shortName: "Intel Corporation",
    regularMarketPrice: 55.37,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: 0.72,
    regularMarketChangePercent: 1.32,
    regularMarketPreviousClose: 54.65,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "DIS",
    shortName: "Walt Disney Company",
    regularMarketPrice: 177.12,
    currency: "USD",
    exchangeName: "NYSE",
    fullExchangeName: "New York Stock Exchange",
    instrumentType: "Equity",
    regularMarketChange: -3.34,
    regularMarketChangePercent: -1.86,
    regularMarketPreviousClose: 180.46,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "KO",
    shortName: "Coca-Cola Company",
    regularMarketPrice: 55.76,
    currency: "USD",
    exchangeName: "NYSE",
    fullExchangeName: "New York Stock Exchange",
    instrumentType: "Equity",
    regularMarketChange: 0.64,
    regularMarketChangePercent: 1.16,
    regularMarketPreviousClose: 55.12,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "PEP",
    shortName: "PepsiCo, Inc.",
    regularMarketPrice: 160.02,
    currency: "USD",
    exchangeName: "NASDAQ",
    fullExchangeName: "NASDAQ Stock Market",
    instrumentType: "Equity",
    regularMarketChange: -1.57,
    regularMarketChangePercent: -0.97,
    regularMarketPreviousClose: 161.59,
    regularMarketTime: 1733323171,
  },
  {
    symbol: "V",
    shortName: "Visa Inc.",
    regularMarketPrice: 246.31,
    currency: "USD",
    exchangeName: "NYSE",
    fullExchangeName: "New York Stock Exchange",
    instrumentType: "Equity",
    regularMarketChange: 4.88,
    regularMarketChangePercent: 2.02,
    regularMarketPreviousClose: 241.43,
    regularMarketTime: 1733323171,
  },
];
